# see https://github.com/compose-spec/compose-spec
# see https://docs.docker.com/compose/overview/
# see https://docs.docker.com/compose/compose-file/
services:
  hello:
    build: hello
    ports:
      # NB since this port is declared as a single integer, docker compose will
      #    automatically allocate a port in the host. to later known the
      #    allocated port use docker compose port hello 8888
      - "8888"
    depends_on:
      etcd:
        condition: service_healthy
    restart: on-failure
    labels:
      # NB you can see these container labels with docker inspect.
      com.example: example
  etcd:
    # see https://etcd.io/docs/v3.6/op-guide/container/#docker
    # see https://github.com/etcd-io/etcd/releases
    # see https://github.com/etcd-io/etcd/blob/v3.6.4/Dockerfile
    # see https://gcr.io/etcd-development/etcd
    image: gcr.io/etcd-development/etcd:v3.6.4
    command:
      - /usr/local/bin/etcd
      - --name=etcd
      - --advertise-client-urls=http://0.0.0.0:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --data-dir=/etcd-data
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health", "--dial-timeout=2s", "--command-timeout=3s"]
      start_period: 5s
      interval: 15s
      timeout: 5s
      retries: 2
    restart: on-failure
    labels:
      # NB you can see these container labels with docker inspect.
      com.example: example
    volumes:
      - etcd-data:/etcd-data
volumes:
  etcd-data:
